(function attachRules(global) {
  const DEFAULT_RULES = {
    phrases: [
      'tony stark mati',
      'tony stark dies',
      'iron man mati',
      'iron man dies',
      'iron man snap',
      'black widow dies',
      'black widow mati',
      'natasha mati',
      'snape kills dumbledore',
      'dumbledore dies',
      'snape bunuh dumbledore',
      'mysterio villain',
      'mysterio pengkhianat',
      'darth vader father',
      'darth vader ayah luke',
      'thanos wins',
      'thanos menang',
      'thanos snap',
      'eren rumbling',
      'eren villain',
      'eren mati',
      'mikasa kills eren',
      'gojo sealed',
      'gojo mati',
      'gojo dies',
      'gojo disegel',
      'sukuna kills gojo',
      'luffy gear 5',
      'luffy joyboy',
      'ace mati',
      'ace dies',
      'itachi mati',
      'jiraiya mati',
      'neji mati',
      'obito is tobi',
      'tobi is obito',
      'aizen villain',
      'lelouch dies',
      'light yagami mati',
      'rengoku mati',
      'makima villain',
      'power mati',
      'aki gun fiend',
      'sasha mati',
      'griffith betray',
      'aerith dies',
      'arthur morgan dies',
      'joel dies',
      'abby kills joel',
      'atreus loki',
      'han solo dies',
      'rey palpatine',
      'batman is bruce wayne',
      'superman dies',
      'ending dia mati',
      'ternyata dia villain',
      'ternyata dia pengkhianat',
      'plot twist dia mati'
    ],
    entities: [
      'tony',
      'tony stark',
      'iron man',
      'black widow',
      'natasha',
      'dumbledore',
      'luke',
      'eren',
      'mikasa',
      'armin',
      'levi',
      'sasha',
      'hange',
      'reiner',
      'bertholdt',
      'annie',
      'gojo',
      'sukuna',
      'luffy',
      'zoro',
      'kaido',
      'big mom',
      'whitebeard',
      'shanks',
      'ace',
      'itachi',
      'jiraiya',
      'neji',
      'naruto',
      'sasuke',
      'madara',
      'obito',
      'tobi',
      'snape',
      'mysterio',
      'thanos',
      'darth vader',
      'vader',
      'palpatine',
      'kylo',
      'han solo',
      'rey',
      'leia',
      'aizen',
      'lelouch',
      'light yagami',
      'kira',
      'rengoku',
      'makima',
      'power',
      'aki',
      'griffith',
      'aerith',
      'arthur morgan',
      'joel',
      'abby',
      'kratos',
      'atreus',
      'batman',
      'bruce wayne',
      'superman',
      'joker'
    ],
    actions: [
      'mati',
      'meninggal',
      'dies',
      'dead',
      'death',
      'tewas',
      'wafat',
      'rip',
      'bunuh',
      'dibunuh',
      'membunuh',
      'killed',
      'kills',
      'murdered',
      'dieksekusi',
      'dikorbankan',
      'sacrifice',
      'kalah',
      'dikalahkan',
      'menang',
      'wins',
      'defeats',
      'defeated',
      'villain',
      'penjahat',
      'jahat',
      'pengkhianat',
      'betray',
      'betrayed',
      'khianat',
      'segel',
      'sealed',
      'disegel',
      'tersegel',
      'reveal',
      'revealed',
      'terungkap',
      'identitas asli',
      'ayah',
      'ibu',
      'father',
      'mother',
      'alive',
      'selamat',
      'hidup',
      'revive',
      'bangkit',
      'awakening',
      'true form',
      'final form',
      'cameo',
      'post credit',
      'ending',
      'akhir',
      'plot twist',
      'rumbling',
      'gear 5',
      'joyboy',
      'hokage',
      'loki',
      'titan',
      'gun fiend'
    ],
    patterns: [
      '.*mati di akhir.*',
      '.*mati pas akhir.*',
      '.*mati nanti.*',
      '.*mati di episode.*',
      '.*mati di chapter.*',
      '.*meninggal di ending.*',
      '.*tewas di ending.*',
      '.*dies.*(ending|akhir).*',
      '.*dead.*(ending|akhir).*',
      '.*ternyata .*(villain|pengkhianat).*',
      '.*ternyata .*(penjahat|jahat).*',
      '.*ternyata .* (mati|meninggal|tewas|wafat).*',
      '.*ternyata .* masih hidup.*',
      '.*dibunuh oleh .*',
      '.*dibunuh sama .*',
      '.*killed by .*',
      '.*kills .* in .*',
      '.*plot twist.*(mati|meninggal|dies|villain).*',
      '.*plot twist.*(tewas|wafat|penjahat|pengkhianat|alive|hidup|selamat).*',
      '.*identitas asli .* adalah.*',
      '.*identitas .* ternyata.*',
      '.*real identity .* is.*',
      '.*akhirnya .* kalah.*',
      '.*akhirnya .* menang.*',
      '.*endingnya .*(mati|meninggal|dies).*',
      '.*endingnya .*(tewas|wafat|dead|kalah|menang|hidup|selamat).*',
      '.*rupanya .*(villain|pengkhianat).*',
      '.*nanti .* (mati|meninggal|tewas|wafat|dies|dead).*',
      '.*nanti .* (kalah|menang|wins|defeated).*',
      '.*nanti .* (disegel|sealed|segel).*',
      '.*episode .* (kalah|dikalahkan|defeated).*',
      '.*episode terakhir .* (kalah|dikalahkan|defeated).*',
      '.*post credit.*(cameo|muncul|appear).*',
      '.*reveal.*(ayah|father|ibu|mother|anak|son|daughter).*',
      '.*jadi villain.*',
      '.*jadi penjahat.*',
      '.*turns evil.*',
      '.*final form.*',
      '.*true form.*',
      '.*awakening.*'
    ]
  };

  async function loadJsonFile(path, fallback) {
    try {
      const url = chrome.runtime.getURL(path);
      const response = await fetch(url);
      if (!response.ok) throw new Error(`Failed to load ${path}`);
      return await response.json();
    } catch (error) {
      console.warn(error.message);
      return fallback;
    }
  }

  async function loadRules() {
    const [phrases, entities, actions, patterns] = await Promise.all([
      loadJsonFile('data/spoiler_phrases.json', DEFAULT_RULES.phrases),
      loadJsonFile('data/spoiler_entities.json', DEFAULT_RULES.entities),
      loadJsonFile('data/spoiler_actions.json', DEFAULT_RULES.actions),
      loadJsonFile('data/spoiler_patterns.json', DEFAULT_RULES.patterns)
    ]);

    return { phrases, entities, actions, patterns };
  }

  global.SpoilerRules = {
    DEFAULT_RULES,
    loadRules
  };
})(typeof window !== 'undefined' ? window : globalThis);
